from openai import OpenAI
import json

def run_actor_critic(api_key: str, task: str, context: str) -> dict:
    """
    Implements the Actor-Critic multi-agent pattern.
    1. Actor Agent generates the initial scientific response.
    2. Critic (Reviewer) Agent evaluates it for accuracy, hallucinated citations, and logic.
    """
    client = OpenAI(api_key=api_key, base_url="https://api.groq.com/openai/v1")
    
    # ACTOR AGENT
    actor_prompt = f"""You are a specialized Scientific Actor Agent.
Task: {task}
Context (Literature/Data): {context}

Generate a rigorous, publication-ready response based ONLY on the context provided.
Do not hallucinate data or citations.
"""
    try:
        actor_res = client.chat.completions.create(
            model="llama3-70b-8192",
            messages=[{"role": "system", "content": "You are a Scientific Generator."},
                      {"role": "user", "content": actor_prompt}],
            temperature=0.3
        )
        draft = actor_res.choices[0].message.content
        
        # CRITIC AGENT
        critic_prompt = f"""You are a strict Scientific Reviewer (Critic Agent).
Evaluate the following Draft generated by another agent based on the provided Context.
Check for:
1. Are there any claims not supported by the Context?
2. Are citations accurate?
3. Is the logic sound?

Context: {context}
Draft to Review:
{draft}

Output your response as JSON with two keys:
- "approved": boolean (true if it passes, false if it contains hallucinations)
- "feedback": string (your critique or corrections)
"""
        critic_res = client.chat.completions.create(
            model="llama3-70b-8192",
            messages=[{"role": "system", "content": "You are a Scientific Critic. Output only raw JSON."},
                      {"role": "user", "content": critic_prompt}],
            response_format={ "type": "json_object" },
            temperature=0.0
        )
        
        raw_content = critic_res.choices[0].message.content
        
        # Clean up markdown backticks if the LLM hallucinated them despite JSON mode
        if raw_content.startswith("```json"):
            raw_content = raw_content[7:-3].strip()
        elif raw_content.startswith("```"):
            raw_content = raw_content[3:-3].strip()
            
        try:
            review = json.loads(raw_content)
        except json.JSONDecodeError:
            review = {"approved": False, "feedback": "JSON parsing error from Critic."}
        
        return {
            "draft": draft,
            "approved": review.get("approved", False),
            "critic_feedback": review.get("feedback", "No feedback.")
        }
        
    except Exception as e:
        return {"error": str(e)}
